name: Build Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          cache: true

      # 🔑 还原 keystore
      - name: Decode Keystore
        run: |
          cd simple_live_app/android
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      # 🔑 写 key.properties
      - name: Create key.properties
        run: |
          cd simple_live_app/android
          cat > key.properties <<EOF
          storeFile=../release.keystore
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          EOF

      - name: Flutter Pub Get
        run: |
          cd simple_live_app
          flutter pub get

      # 🚀 构建 Release
      - name: Build Release APK
        run: |
          cd simple_live_app
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-release-apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
